/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  FeatureFlag,
  Vendor,
  VendorCreate
} from '.././orval-schemas'
import { orvalMutator } from '../../../orval-mutator';



/**
 * @summary Liveness/Readiness
 */
export const getActuatorHealth = (
    
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<void>(
      {url: `/actuator/health`, method: 'GET', signal
    },
      );
    }
  

export const getGetActuatorHealthQueryKey = () => {
    return [`/actuator/health`] as const;
    }

    
export const getGetActuatorHealthQueryOptions = <TData = Awaited<ReturnType<typeof getActuatorHealth>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getActuatorHealth>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActuatorHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActuatorHealth>>> = ({ signal }) => getActuatorHealth(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActuatorHealth>>, TError, TData> & { queryKey: QueryKey }
}

export type GetActuatorHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getActuatorHealth>>>
export type GetActuatorHealthQueryError = unknown

/**
 * @summary Liveness/Readiness
 */
export const useGetActuatorHealth = <TData = Awaited<ReturnType<typeof getActuatorHealth>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getActuatorHealth>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetActuatorHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary List feature flags
 */
export const getFlags = (
    
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<FeatureFlag[]>(
      {url: `/flags`, method: 'GET', signal
    },
      );
    }
  

export const getGetFlagsQueryKey = () => {
    return [`/flags`] as const;
    }

    
export const getGetFlagsQueryOptions = <TData = Awaited<ReturnType<typeof getFlags>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFlags>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlagsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlags>>> = ({ signal }) => getFlags(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlags>>, TError, TData> & { queryKey: QueryKey }
}

export type GetFlagsQueryResult = NonNullable<Awaited<ReturnType<typeof getFlags>>>
export type GetFlagsQueryError = unknown

/**
 * @summary List feature flags
 */
export const useGetFlags = <TData = Awaited<ReturnType<typeof getFlags>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFlags>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetFlagsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create vendor (Ops)
 */
export const postVendors = (
    vendorCreate: VendorCreate,
 ) => {
      
      
      return orvalMutator<Vendor>(
      {url: `/vendors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: vendorCreate
    },
      );
    }
  


export const getPostVendorsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVendors>>, TError,{data: VendorCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postVendors>>, TError,{data: VendorCreate}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postVendors>>, {data: VendorCreate}> = (props) => {
          const {data} = props ?? {};

          return  postVendors(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostVendorsMutationResult = NonNullable<Awaited<ReturnType<typeof postVendors>>>
    export type PostVendorsMutationBody = VendorCreate
    export type PostVendorsMutationError = unknown

    /**
 * @summary Create vendor (Ops)
 */
export const usePostVendors = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVendors>>, TError,{data: VendorCreate}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postVendors>>,
        TError,
        {data: VendorCreate},
        TContext
      > => {

      const mutationOptions = getPostVendorsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    