/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetProductsParams,
  PaginatedProducts,
  Product,
  ProductCreate
} from '.././orval-schemas'
import { orvalMutator } from '../../../orval-mutator';



/**
 * @summary Browse products
 */
export const getProducts = (
    params?: GetProductsParams,
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<PaginatedProducts>(
      {url: `/products`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetProductsQueryKey = (params?: GetProductsParams,) => {
    return [`/products`, ...(params ? [params]: [])] as const;
    }

    
export const getGetProductsQueryOptions = <TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(params?: GetProductsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({ signal }) => getProducts(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>
export type GetProductsQueryError = unknown

/**
 * @summary Browse products
 */
export const useGetProducts = <TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: GetProductsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetProductsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create product (Ops or Vendor)
 */
export const postProducts = (
    productCreate: ProductCreate,
 ) => {
      
      
      return orvalMutator<Product>(
      {url: `/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productCreate
    },
      );
    }
  


export const getPostProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: ProductCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: ProductCreate}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProducts>>, {data: ProductCreate}> = (props) => {
          const {data} = props ?? {};

          return  postProducts(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postProducts>>>
    export type PostProductsMutationBody = ProductCreate
    export type PostProductsMutationError = unknown

    /**
 * @summary Create product (Ops or Vendor)
 */
export const usePostProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: ProductCreate}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postProducts>>,
        TError,
        {data: ProductCreate},
        TContext
      > => {

      const mutationOptions = getPostProductsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get a product
 */
export const getProductsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<Product>(
      {url: `/products/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetProductsIdQueryKey = (id: string,) => {
    return [`/products/${id}`] as const;
    }

    
export const getGetProductsIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductsId>>, TError = unknown>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProductsId>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductsId>>> = ({ signal }) => getProductsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProductsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsId>>>
export type GetProductsIdQueryError = unknown

/**
 * @summary Get a product
 */
export const useGetProductsId = <TData = Awaited<ReturnType<typeof getProductsId>>, TError = unknown>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProductsId>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetProductsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



