/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  PostWalletsOrgIdTopupsBody,
  Wallet,
  WalletTransaction
} from '.././orval-schemas'
import { orvalMutator } from '../../../orval-mutator';



/**
 * @summary Get wallet balance
 */
export const getWalletsOrgId = (
    orgId: string,
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<Wallet>(
      {url: `/wallets/${orgId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetWalletsOrgIdQueryKey = (orgId: string,) => {
    return [`/wallets/${orgId}`] as const;
    }

    
export const getGetWalletsOrgIdQueryOptions = <TData = Awaited<ReturnType<typeof getWalletsOrgId>>, TError = unknown>(orgId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWalletsOrgId>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletsOrgIdQueryKey(orgId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletsOrgId>>> = ({ signal }) => getWalletsOrgId(orgId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletsOrgId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWalletsOrgIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletsOrgId>>>
export type GetWalletsOrgIdQueryError = unknown

/**
 * @summary Get wallet balance
 */
export const useGetWalletsOrgId = <TData = Awaited<ReturnType<typeof getWalletsOrgId>>, TError = unknown>(
 orgId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWalletsOrgId>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetWalletsOrgIdQueryOptions(orgId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Top-up wallet (Ops/Finance)
 */
export const postWalletsOrgIdTopups = (
    orgId: string,
    postWalletsOrgIdTopupsBody: PostWalletsOrgIdTopupsBody,
 ) => {
      
      
      return orvalMutator<WalletTransaction>(
      {url: `/wallets/${orgId}/topups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postWalletsOrgIdTopupsBody
    },
      );
    }
  


export const getPostWalletsOrgIdTopupsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWalletsOrgIdTopups>>, TError,{orgId: string;data: PostWalletsOrgIdTopupsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postWalletsOrgIdTopups>>, TError,{orgId: string;data: PostWalletsOrgIdTopupsBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWalletsOrgIdTopups>>, {orgId: string;data: PostWalletsOrgIdTopupsBody}> = (props) => {
          const {orgId,data} = props ?? {};

          return  postWalletsOrgIdTopups(orgId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWalletsOrgIdTopupsMutationResult = NonNullable<Awaited<ReturnType<typeof postWalletsOrgIdTopups>>>
    export type PostWalletsOrgIdTopupsMutationBody = PostWalletsOrgIdTopupsBody
    export type PostWalletsOrgIdTopupsMutationError = unknown

    /**
 * @summary Top-up wallet (Ops/Finance)
 */
export const usePostWalletsOrgIdTopups = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWalletsOrgIdTopups>>, TError,{orgId: string;data: PostWalletsOrgIdTopupsBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postWalletsOrgIdTopups>>,
        TError,
        {orgId: string;data: PostWalletsOrgIdTopupsBody},
        TContext
      > => {

      const mutationOptions = getPostWalletsOrgIdTopupsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    