/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import type { ProductCreateAttributes } from './productCreateAttributes';

export interface ProductCreate {
  attributes?: ProductCreateAttributes;
  category?: string;
  description?: string;
  mediaUrls?: string[];
  name: string;
  referencePrice?: number;
  sku: string;
  vendorId: string;
}
