/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import type { QuoteLineCreate } from './quoteLineCreate';

export interface QuoteCreate {
  currency: string;
  lines: QuoteLineCreate[];
  notes?: string;
  validUntil?: string;
  vendorId: string;
}
