/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import type { Attachment } from './attachment';
import type { RFQLine } from './rFQLine';
import type { RfqStatus } from './rfqStatus';

export interface Rfq {
  attachments?: Attachment[];
  buyerId?: string;
  id?: string;
  lines?: RFQLine[];
  notes?: string;
  status?: RfqStatus;
  title?: string;
}
