package com.p4.backend.shared.response;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.Map;

/**
 * Represents RFC7807 Problem Details for HTTP APIs.
 * This class provides a standard way to carry machine-readable details of errors in HTTP API responses.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProblemDetails {

    /**
     * A URI reference that identifies the problem type.
     * This specification encourages clients to use the type field to
     * understand the semantics of the problem.
     */
    private String type;

    /**
     * A short, human-readable summary of the problem that SHOULD NOT change
     * from occurrence to occurrence of the problem, except for purposes of
     * localization.
     */
    private String title;

    /**
     * The HTTP status code generated by the origin server for this occurrence
     * of the problem.
     */
    private Integer status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * It may or may not yield further information if dereferenced.
     */
    private String instance;

    /**
     * An error code specific to the API implementation.
     */
    @JsonProperty("error_code")
    private String errorCode;

    /**
     * Additional properties that can be included in the problem details.
     */
    private Map<String, Object> additionalProperties;

    /**
     * Timestamp of when the problem occurred.
     */
    private Instant timestamp;

    /**
     * Creates a ProblemDetails instance with all required fields.
     *
     * @param type The problem type URI
     * @param title A short summary of the problem
     * @param status The HTTP status code
     * @param detail A human-readable explanation of the problem
     */
    public static ProblemDetails create(String type, String title, Integer status, String detail) {
        return ProblemDetails.builder()
                .type(type)
                .title(title)
                .status(status)
                .detail(detail)
                .timestamp(Instant.now())
                .build();
    }

    /**
     * Creates a ProblemDetails instance for a client error (4xx).
     *
     * @param title A short summary of the problem
     * @param detail A human-readable explanation of the problem
     * @return ProblemDetails instance
     */
    public static ProblemDetails clientError(String title, String detail) {
        return create("about:blank", title, 400, detail);
    }

    /**
     * Creates a ProblemDetails instance for a server error (5xx).
     *
     * @param title A short summary of the problem
     * @param detail A human-readable explanation of the problem
     * @return ProblemDetails instance
     */
    public static ProblemDetails serverError(String title, String detail) {
        return create("about:blank", title, 500, detail);
    }

    /**
     * Creates a ProblemDetails instance for validation errors.
     *
     * @param detail A human-readable explanation of the validation errors
     * @return ProblemDetails instance
     */
    public static ProblemDetails validationError(String detail) {
        return create("about:blank", "Validation Failed", 400, detail);
    }

    /**
     * Creates a ProblemDetails instance for not found errors.
     *
     * @param resource The name of the resource that was not found
     * @return ProblemDetails instance
     */
    public static ProblemDetails notFound(String resource) {
        return create("about:blank", "Not Found", 404, resource + " was not found");
    }
}