/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  FeatureFlag,
  GetProductsParams,
  JwtResponse,
  LoginRequest,
  Order,
  PaginatedProducts,
  Payment,
  PostOrdersBody,
  PostOrdersOrderIdPayWalletBody,
  PostWalletsOrgIdTopupsBody,
  Product,
  ProductCreate,
  Quote,
  QuoteCreate,
  RFQCreate,
  RFQLine,
  RFQLineCreate,
  RegisterRequest,
  Rfq,
  User,
  Vendor,
  VendorCreate,
  Wallet,
  WalletTransaction,
} from './schemas';
import { httpMutator } from './mutator';

/**
 * @summary Liveness/Readiness
 */
export const getActuatorHealth = (signal?: AbortSignal) => {
  return httpMutator<void>({ url: `/actuator/health`, method: 'GET', signal });
};

export const getGetActuatorHealthQueryKey = () => {
  return [`/actuator/health`] as const;
};

export const getGetActuatorHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getActuatorHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getActuatorHealth>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetActuatorHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getActuatorHealth>>> = ({ signal }) =>
    getActuatorHealth(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getActuatorHealth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetActuatorHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getActuatorHealth>>
>;
export type GetActuatorHealthQueryError = unknown;

/**
 * @summary Liveness/Readiness
 */
export const useGetActuatorHealth = <
  TData = Awaited<ReturnType<typeof getActuatorHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getActuatorHealth>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetActuatorHealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary User login
 */
export const postAuthLogin = (loginRequest: LoginRequest) => {
  return httpMutator<JwtResponse>({
    url: `/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginRequest,
  });
};

export const getPostAuthLoginMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data: LoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>;
export type PostAuthLoginMutationBody = LoginRequest;
export type PostAuthLoginMutationError = void;

/**
 * @summary User login
 */
export const usePostAuthLogin = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationOptions = getPostAuthLoginMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary User registration
 */
export const postAuthRegister = (registerRequest: RegisterRequest) => {
  return httpMutator<JwtResponse>({
    url: `/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerRequest,
  });
};

export const getPostAuthRegisterMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRegister>>,
    { data: RegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationBody = RegisterRequest;
export type PostAuthRegisterMutationError = void;

/**
 * @summary User registration
 */
export const usePostAuthRegister = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const mutationOptions = getPostAuthRegisterMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Get current user
 */
export const getUsersMe = (signal?: AbortSignal) => {
  return httpMutator<User>({ url: `/users/me`, method: 'GET', signal });
};

export const getGetUsersMeQueryKey = () => {
  return [`/users/me`] as const;
};

export const getGetUsersMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersMe>>,
  TError = void,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersMe>>> = ({ signal }) =>
    getUsersMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUsersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersMe>>>;
export type GetUsersMeQueryError = void;

/**
 * @summary Get current user
 */
export const useGetUsersMe = <
  TData = Awaited<ReturnType<typeof getUsersMe>>,
  TError = void,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetUsersMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary List feature flags
 */
export const getFlags = (signal?: AbortSignal) => {
  return httpMutator<FeatureFlag[]>({ url: `/flags`, method: 'GET', signal });
};

export const getGetFlagsQueryKey = () => {
  return [`/flags`] as const;
};

export const getGetFlagsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFlags>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlags>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFlagsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlags>>> = ({ signal }) =>
    getFlags(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFlags>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFlagsQueryResult = NonNullable<Awaited<ReturnType<typeof getFlags>>>;
export type GetFlagsQueryError = unknown;

/**
 * @summary List feature flags
 */
export const useGetFlags = <
  TData = Awaited<ReturnType<typeof getFlags>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlags>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetFlagsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Browse products
 */
export const getProducts = (params?: GetProductsParams, signal?: AbortSignal) => {
  return httpMutator<PaginatedProducts>({ url: `/products`, method: 'GET', params, signal });
};

export const getGetProductsQueryKey = (params?: GetProductsParams) => {
  return [`/products`, ...(params ? [params] : [])] as const;
};

export const getGetProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = unknown,
>(
  params?: GetProductsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({ signal }) =>
    getProducts(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProducts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>;
export type GetProductsQueryError = unknown;

/**
 * @summary Browse products
 */
export const useGetProducts = <TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
  params?: GetProductsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetProductsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Create product (Ops or Vendor)
 */
export const postProducts = (productCreate: ProductCreate) => {
  return httpMutator<Product>({
    url: `/products`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: productCreate,
  });
};

export const getPostProductsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProducts>>,
    TError,
    { data: ProductCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProducts>>,
  TError,
  { data: ProductCreate },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProducts>>,
    { data: ProductCreate }
  > = (props) => {
    const { data } = props ?? {};

    return postProducts(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postProducts>>>;
export type PostProductsMutationBody = ProductCreate;
export type PostProductsMutationError = unknown;

/**
 * @summary Create product (Ops or Vendor)
 */
export const usePostProducts = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProducts>>,
    TError,
    { data: ProductCreate },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postProducts>>,
  TError,
  { data: ProductCreate },
  TContext
> => {
  const mutationOptions = getPostProductsMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Get a product
 */
export const getProductsId = (id: string, signal?: AbortSignal) => {
  return httpMutator<Product>({ url: `/products/${id}`, method: 'GET', signal });
};

export const getGetProductsIdQueryKey = (id: string) => {
  return [`/products/${id}`] as const;
};

export const getGetProductsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductsId>>> = ({ signal }) =>
    getProductsId(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductsId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProductsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsId>>>;
export type GetProductsIdQueryError = unknown;

/**
 * @summary Get a product
 */
export const useGetProductsId = <
  TData = Awaited<ReturnType<typeof getProductsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsId>>, TError, TData>>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetProductsIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Create vendor (Ops)
 */
export const postVendors = (vendorCreate: VendorCreate) => {
  return httpMutator<Vendor>({
    url: `/vendors`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: vendorCreate,
  });
};

export const getPostVendorsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postVendors>>,
    TError,
    { data: VendorCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postVendors>>,
  TError,
  { data: VendorCreate },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postVendors>>,
    { data: VendorCreate }
  > = (props) => {
    const { data } = props ?? {};

    return postVendors(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostVendorsMutationResult = NonNullable<Awaited<ReturnType<typeof postVendors>>>;
export type PostVendorsMutationBody = VendorCreate;
export type PostVendorsMutationError = unknown;

/**
 * @summary Create vendor (Ops)
 */
export const usePostVendors = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postVendors>>,
    TError,
    { data: VendorCreate },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postVendors>>,
  TError,
  { data: VendorCreate },
  TContext
> => {
  const mutationOptions = getPostVendorsMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Create RFQ (Buyer)
 */
export const postRfqs = (rFQCreate: RFQCreate) => {
  return httpMutator<Rfq>({
    url: `/rfqs`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: rFQCreate,
  });
};

export const getPostRfqsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqs>>,
    TError,
    { data: RFQCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRfqs>>,
  TError,
  { data: RFQCreate },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRfqs>>, { data: RFQCreate }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postRfqs(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRfqsMutationResult = NonNullable<Awaited<ReturnType<typeof postRfqs>>>;
export type PostRfqsMutationBody = RFQCreate;
export type PostRfqsMutationError = unknown;

/**
 * @summary Create RFQ (Buyer)
 */
export const usePostRfqs = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqs>>,
    TError,
    { data: RFQCreate },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postRfqs>>,
  TError,
  { data: RFQCreate },
  TContext
> => {
  const mutationOptions = getPostRfqsMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Get RFQ
 */
export const getRfqsRfqId = (rfqId: string, signal?: AbortSignal) => {
  return httpMutator<Rfq>({ url: `/rfqs/${rfqId}`, method: 'GET', signal });
};

export const getGetRfqsRfqIdQueryKey = (rfqId: string) => {
  return [`/rfqs/${rfqId}`] as const;
};

export const getGetRfqsRfqIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getRfqsRfqId>>,
  TError = unknown,
>(
  rfqId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRfqsRfqIdQueryKey(rfqId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRfqsRfqId>>> = ({ signal }) =>
    getRfqsRfqId(rfqId, signal);

  return { queryKey, queryFn, enabled: !!rfqId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRfqsRfqId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRfqsRfqIdQueryResult = NonNullable<Awaited<ReturnType<typeof getRfqsRfqId>>>;
export type GetRfqsRfqIdQueryError = unknown;

/**
 * @summary Get RFQ
 */
export const useGetRfqsRfqId = <TData = Awaited<ReturnType<typeof getRfqsRfqId>>, TError = unknown>(
  rfqId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqId>>, TError, TData>>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetRfqsRfqIdQueryOptions(rfqId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Add RFQ line
 */
export const postRfqsRfqIdLines = (rfqId: string, rFQLineCreate: RFQLineCreate) => {
  return httpMutator<RFQLine>({
    url: `/rfqs/${rfqId}/lines`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: rFQLineCreate,
  });
};

export const getPostRfqsRfqIdLinesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdLines>>,
    TError,
    { rfqId: string; data: RFQLineCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRfqsRfqIdLines>>,
  TError,
  { rfqId: string; data: RFQLineCreate },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRfqsRfqIdLines>>,
    { rfqId: string; data: RFQLineCreate }
  > = (props) => {
    const { rfqId, data } = props ?? {};

    return postRfqsRfqIdLines(rfqId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRfqsRfqIdLinesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRfqsRfqIdLines>>
>;
export type PostRfqsRfqIdLinesMutationBody = RFQLineCreate;
export type PostRfqsRfqIdLinesMutationError = unknown;

/**
 * @summary Add RFQ line
 */
export const usePostRfqsRfqIdLines = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdLines>>,
    TError,
    { rfqId: string; data: RFQLineCreate },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postRfqsRfqIdLines>>,
  TError,
  { rfqId: string; data: RFQLineCreate },
  TContext
> => {
  const mutationOptions = getPostRfqsRfqIdLinesMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Issue RFQ (moves from draft→issued)
 */
export const postRfqsRfqIdIssue = (rfqId: string) => {
  return httpMutator<void>({ url: `/rfqs/${rfqId}/issue`, method: 'POST' });
};

export const getPostRfqsRfqIdIssueMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdIssue>>,
    TError,
    { rfqId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRfqsRfqIdIssue>>,
  TError,
  { rfqId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRfqsRfqIdIssue>>,
    { rfqId: string }
  > = (props) => {
    const { rfqId } = props ?? {};

    return postRfqsRfqIdIssue(rfqId);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRfqsRfqIdIssueMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRfqsRfqIdIssue>>
>;

export type PostRfqsRfqIdIssueMutationError = unknown;

/**
 * @summary Issue RFQ (moves from draft→issued)
 */
export const usePostRfqsRfqIdIssue = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdIssue>>,
    TError,
    { rfqId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postRfqsRfqIdIssue>>,
  TError,
  { rfqId: string },
  TContext
> => {
  const mutationOptions = getPostRfqsRfqIdIssueMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary List quotes for RFQ (Buyer view)
 */
export const getRfqsRfqIdQuotes = (rfqId: string, signal?: AbortSignal) => {
  return httpMutator<Quote[]>({ url: `/rfqs/${rfqId}/quotes`, method: 'GET', signal });
};

export const getGetRfqsRfqIdQuotesQueryKey = (rfqId: string) => {
  return [`/rfqs/${rfqId}/quotes`] as const;
};

export const getGetRfqsRfqIdQuotesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>,
  TError = unknown,
>(
  rfqId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRfqsRfqIdQuotesQueryKey(rfqId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>> = ({ signal }) =>
    getRfqsRfqIdQuotes(rfqId, signal);

  return { queryKey, queryFn, enabled: !!rfqId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRfqsRfqIdQuotesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>
>;
export type GetRfqsRfqIdQuotesQueryError = unknown;

/**
 * @summary List quotes for RFQ (Buyer view)
 */
export const useGetRfqsRfqIdQuotes = <
  TData = Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>,
  TError = unknown,
>(
  rfqId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>, TError, TData>>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetRfqsRfqIdQuotesQueryOptions(rfqId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Submit quote (Vendor)
 */
export const postRfqsRfqIdQuotes = (rfqId: string, quoteCreate: QuoteCreate) => {
  return httpMutator<Quote>({
    url: `/rfqs/${rfqId}/quotes`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: quoteCreate,
  });
};

export const getPostRfqsRfqIdQuotesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>,
    TError,
    { rfqId: string; data: QuoteCreate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>,
  TError,
  { rfqId: string; data: QuoteCreate },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>,
    { rfqId: string; data: QuoteCreate }
  > = (props) => {
    const { rfqId, data } = props ?? {};

    return postRfqsRfqIdQuotes(rfqId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRfqsRfqIdQuotesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>
>;
export type PostRfqsRfqIdQuotesMutationBody = QuoteCreate;
export type PostRfqsRfqIdQuotesMutationError = unknown;

/**
 * @summary Submit quote (Vendor)
 */
export const usePostRfqsRfqIdQuotes = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>,
    TError,
    { rfqId: string; data: QuoteCreate },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>,
  TError,
  { rfqId: string; data: QuoteCreate },
  TContext
> => {
  const mutationOptions = getPostRfqsRfqIdQuotesMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Buyer accepts a quote (awards RFQ)
 */
export const postRfqsRfqIdQuotesQuoteIdAccept = (rfqId: string, quoteId: string) => {
  return httpMutator<void>({ url: `/rfqs/${rfqId}/quotes/${quoteId}/accept`, method: 'POST' });
};

export const getPostRfqsRfqIdQuotesQuoteIdAcceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>,
    TError,
    { rfqId: string; quoteId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>,
  TError,
  { rfqId: string; quoteId: string },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>,
    { rfqId: string; quoteId: string }
  > = (props) => {
    const { rfqId, quoteId } = props ?? {};

    return postRfqsRfqIdQuotesQuoteIdAccept(rfqId, quoteId);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRfqsRfqIdQuotesQuoteIdAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>
>;

export type PostRfqsRfqIdQuotesQuoteIdAcceptMutationError = unknown;

/**
 * @summary Buyer accepts a quote (awards RFQ)
 */
export const usePostRfqsRfqIdQuotesQuoteIdAccept = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>,
    TError,
    { rfqId: string; quoteId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>,
  TError,
  { rfqId: string; quoteId: string },
  TContext
> => {
  const mutationOptions = getPostRfqsRfqIdQuotesQuoteIdAcceptMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Create order from accepted quote
 */
export const postOrders = (postOrdersBody: PostOrdersBody) => {
  return httpMutator<Order>({
    url: `/orders`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postOrdersBody,
  });
};

export const getPostOrdersMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOrders>>,
    TError,
    { data: PostOrdersBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOrders>>,
  TError,
  { data: PostOrdersBody },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOrders>>,
    { data: PostOrdersBody }
  > = (props) => {
    const { data } = props ?? {};

    return postOrders(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOrdersMutationResult = NonNullable<Awaited<ReturnType<typeof postOrders>>>;
export type PostOrdersMutationBody = PostOrdersBody;
export type PostOrdersMutationError = unknown;

/**
 * @summary Create order from accepted quote
 */
export const usePostOrders = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOrders>>,
    TError,
    { data: PostOrdersBody },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postOrders>>,
  TError,
  { data: PostOrdersBody },
  TContext
> => {
  const mutationOptions = getPostOrdersMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Get order
 */
export const getOrdersOrderId = (orderId: string, signal?: AbortSignal) => {
  return httpMutator<Order>({ url: `/orders/${orderId}`, method: 'GET', signal });
};

export const getGetOrdersOrderIdQueryKey = (orderId: string) => {
  return [`/orders/${orderId}`] as const;
};

export const getGetOrdersOrderIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrdersOrderId>>,
  TError = unknown,
>(
  orderId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersOrderId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOrdersOrderIdQueryKey(orderId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrdersOrderId>>> = ({ signal }) =>
    getOrdersOrderId(orderId, signal);

  return { queryKey, queryFn, enabled: !!orderId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrdersOrderId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOrdersOrderIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrdersOrderId>>>;
export type GetOrdersOrderIdQueryError = unknown;

/**
 * @summary Get order
 */
export const useGetOrdersOrderId = <
  TData = Awaited<ReturnType<typeof getOrdersOrderId>>,
  TError = unknown,
>(
  orderId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersOrderId>>, TError, TData>>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetOrdersOrderIdQueryOptions(orderId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Pay order using wallet
 */
export const postOrdersOrderIdPayWallet = (
  orderId: string,
  postOrdersOrderIdPayWalletBody: PostOrdersOrderIdPayWalletBody,
) => {
  return httpMutator<Payment>({
    url: `/orders/${orderId}/pay/wallet`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postOrdersOrderIdPayWalletBody,
  });
};

export const getPostOrdersOrderIdPayWalletMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>,
    TError,
    { orderId: string; data: PostOrdersOrderIdPayWalletBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>,
  TError,
  { orderId: string; data: PostOrdersOrderIdPayWalletBody },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>,
    { orderId: string; data: PostOrdersOrderIdPayWalletBody }
  > = (props) => {
    const { orderId, data } = props ?? {};

    return postOrdersOrderIdPayWallet(orderId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOrdersOrderIdPayWalletMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>
>;
export type PostOrdersOrderIdPayWalletMutationBody = PostOrdersOrderIdPayWalletBody;
export type PostOrdersOrderIdPayWalletMutationError = unknown;

/**
 * @summary Pay order using wallet
 */
export const usePostOrdersOrderIdPayWallet = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>,
    TError,
    { orderId: string; data: PostOrdersOrderIdPayWalletBody },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>,
  TError,
  { orderId: string; data: PostOrdersOrderIdPayWalletBody },
  TContext
> => {
  const mutationOptions = getPostOrdersOrderIdPayWalletMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Get wallet balance
 */
export const getWalletsOrgId = (orgId: string, signal?: AbortSignal) => {
  return httpMutator<Wallet>({ url: `/wallets/${orgId}`, method: 'GET', signal });
};

export const getGetWalletsOrgIdQueryKey = (orgId: string) => {
  return [`/wallets/${orgId}`] as const;
};

export const getGetWalletsOrgIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getWalletsOrgId>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletsOrgId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWalletsOrgIdQueryKey(orgId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletsOrgId>>> = ({ signal }) =>
    getWalletsOrgId(orgId, signal);

  return { queryKey, queryFn, enabled: !!orgId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWalletsOrgId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWalletsOrgIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletsOrgId>>>;
export type GetWalletsOrgIdQueryError = unknown;

/**
 * @summary Get wallet balance
 */
export const useGetWalletsOrgId = <
  TData = Awaited<ReturnType<typeof getWalletsOrgId>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletsOrgId>>, TError, TData>>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetWalletsOrgIdQueryOptions(orgId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Top-up wallet (Ops/Finance)
 */
export const postWalletsOrgIdTopups = (
  orgId: string,
  postWalletsOrgIdTopupsBody: PostWalletsOrgIdTopupsBody,
) => {
  return httpMutator<WalletTransaction>({
    url: `/wallets/${orgId}/topups`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postWalletsOrgIdTopupsBody,
  });
};

export const getPostWalletsOrgIdTopupsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postWalletsOrgIdTopups>>,
    TError,
    { orgId: string; data: PostWalletsOrgIdTopupsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postWalletsOrgIdTopups>>,
  TError,
  { orgId: string; data: PostWalletsOrgIdTopupsBody },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postWalletsOrgIdTopups>>,
    { orgId: string; data: PostWalletsOrgIdTopupsBody }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return postWalletsOrgIdTopups(orgId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostWalletsOrgIdTopupsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postWalletsOrgIdTopups>>
>;
export type PostWalletsOrgIdTopupsMutationBody = PostWalletsOrgIdTopupsBody;
export type PostWalletsOrgIdTopupsMutationError = unknown;

/**
 * @summary Top-up wallet (Ops/Finance)
 */
export const usePostWalletsOrgIdTopups = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postWalletsOrgIdTopups>>,
    TError,
    { orgId: string; data: PostWalletsOrgIdTopupsBody },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postWalletsOrgIdTopups>>,
  TError,
  { orgId: string; data: PostWalletsOrgIdTopupsBody },
  TContext
> => {
  const mutationOptions = getPostWalletsOrgIdTopupsMutationOptions(options);

  return useMutation(mutationOptions);
};
