/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/actuator/health": {
    /** Liveness/Readiness */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/auth/login": {
    /** User login */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          content: {
            "application/json": components["schemas"]["JwtResponse"];
          };
        };
        /** @description Invalid credentials */
        401: {
          content: never;
        };
      };
    };
  };
  "/auth/register": {
    /** User registration */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description Registration successful */
        200: {
          content: {
            "application/json": components["schemas"]["JwtResponse"];
          };
        };
        /** @description Email already exists */
        409: {
          content: never;
        };
      };
    };
  };
  "/users/me": {
    /** Get current user */
    get: {
      responses: {
        /** @description Current user details */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
      };
    };
  };
  "/flags": {
    /** List feature flags */
    get: {
      responses: {
        /** @description Flags */
        200: {
          content: {
            "application/json": components["schemas"]["FeatureFlag"][];
          };
        };
      };
    };
  };
  "/products": {
    /** Browse products */
    get: {
      parameters: {
        query?: {
          q?: string;
          category?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description Product list */
        200: {
          content: {
            "application/json": components["schemas"]["PaginatedProducts"];
          };
        };
      };
    };
    /** Create product (Ops or Vendor) */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProductCreate"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["Product"];
          };
        };
      };
    };
  };
  "/products/{id}": {
    /** Get a product */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Product */
        200: {
          content: {
            "application/json": components["schemas"]["Product"];
          };
        };
      };
    };
  };
  "/vendors": {
    /** Create vendor (Ops) */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["VendorCreate"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["Vendor"];
          };
        };
      };
    };
  };
  "/rfqs": {
    /** Create RFQ (Buyer) */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RFQCreate"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["RFQ"];
          };
        };
      };
    };
  };
  "/rfqs/{rfqId}": {
    /** Get RFQ */
    get: {
      parameters: {
        path: {
          rfqId: string;
        };
      };
      responses: {
        /** @description RFQ */
        200: {
          content: {
            "application/json": components["schemas"]["RFQ"];
          };
        };
      };
    };
  };
  "/rfqs/{rfqId}/lines": {
    /** Add RFQ line */
    post: {
      parameters: {
        path: {
          rfqId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RFQLineCreate"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["RFQLine"];
          };
        };
      };
    };
  };
  "/rfqs/{rfqId}/issue": {
    /** Issue RFQ (moves from draft→issued) */
    post: {
      parameters: {
        path: {
          rfqId: string;
        };
      };
      responses: {
        /** @description Issued */
        200: {
          content: never;
        };
      };
    };
  };
  "/rfqs/{rfqId}/quotes": {
    /** List quotes for RFQ (Buyer view) */
    get: {
      parameters: {
        path: {
          rfqId: string;
        };
      };
      responses: {
        /** @description Quotes */
        200: {
          content: {
            "application/json": components["schemas"]["Quote"][];
          };
        };
      };
    };
    /** Submit quote (Vendor) */
    post: {
      parameters: {
        path: {
          rfqId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["QuoteCreate"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["Quote"];
          };
        };
      };
    };
  };
  "/rfqs/{rfqId}/quotes/{quoteId}/accept": {
    /** Buyer accepts a quote (awards RFQ) */
    post: {
      parameters: {
        path: {
          rfqId: string;
          quoteId: string;
        };
      };
      responses: {
        /** @description Accepted */
        200: {
          content: never;
        };
      };
    };
  };
  "/orders": {
    /** Create order from accepted quote */
    post: {
      requestBody: {
        content: {
          "application/json": {
            quoteId: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["Order"];
          };
        };
      };
    };
  };
  "/orders/{orderId}": {
    /** Get order */
    get: {
      parameters: {
        path: {
          orderId: string;
        };
      };
      responses: {
        /** @description Order */
        200: {
          content: {
            "application/json": components["schemas"]["Order"];
          };
        };
      };
    };
  };
  "/orders/{orderId}/pay/wallet": {
    /** Pay order using wallet */
    post: {
      parameters: {
        path: {
          orderId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            idempotencyKey?: string;
          };
        };
      };
      responses: {
        /** @description Payment result */
        200: {
          content: {
            "application/json": components["schemas"]["Payment"];
          };
        };
      };
    };
  };
  "/wallets/{orgId}": {
    /** Get wallet balance */
    get: {
      parameters: {
        path: {
          orgId: string;
        };
      };
      responses: {
        /** @description Wallet */
        200: {
          content: {
            "application/json": components["schemas"]["Wallet"];
          };
        };
      };
    };
  };
  "/wallets/{orgId}/topups": {
    /** Top-up wallet (Ops/Finance) */
    post: {
      parameters: {
        path: {
          orgId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: double */
            amount: number;
            /** @default USD */
            currency: string;
          };
        };
      };
      responses: {
        /** @description Topup transaction */
        201: {
          content: {
            "application/json": components["schemas"]["WalletTransaction"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    LoginRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * Format: password
       * @example password123
       */
      password: string;
    };
    RegisterRequest: {
      /** @example John Doe */
      fullName: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * Format: password
       * @example password123
       */
      password: string;
      /** @example 01G1JQZ9852D3E4F5G6H7J8K9L0 */
      orgId: string;
    };
    JwtResponse: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      token?: string;
      /** @example Bearer */
      type?: string;
      /** @example 01G1JQZ9852D3E4F5G6H7J8K9L0 */
      id?: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email?: string;
      /** @example John Doe */
      fullName?: string;
      /**
       * @example buyer
       * @enum {string}
       */
      role?: "buyer" | "vendor" | "ops" | "admin";
    };
    User: {
      /** @example 01G1JQZ9852D3E4F5G6H7J8K9L0 */
      id?: string;
      /** @example 01G1JQZ9852D3E4F5G6H7J8K9M1 */
      orgId?: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email?: string;
      /** @example John Doe */
      fullName?: string;
      /**
       * @example buyer
       * @enum {string}
       */
      role?: "buyer" | "vendor" | "ops" | "admin";
      /** @example true */
      isActive?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    FeatureFlag: {
      key?: string;
      value?: Record<string, never>;
    };
    VendorCreate: {
      name: string;
    };
    Vendor: {
      id?: string;
      name?: string;
      /** @example vendor */
      role?: string;
    };
    ProductCreate: {
      vendorId: string;
      sku: string;
      name: string;
      description?: string;
      category?: string;
      /** Format: double */
      referencePrice?: number;
      mediaUrls?: string[];
      attributes?: Record<string, never>;
    };
    Product: {
      id?: string;
      vendorId?: string;
      sku?: string;
      name?: string;
      description?: string;
      category?: string;
      /** Format: double */
      referencePrice?: number;
      mediaUrls?: string[];
      attributes?: Record<string, never>;
    };
    PaginatedProducts: {
      items?: components["schemas"]["Product"][];
      page?: number;
      pageSize?: number;
      total?: number;
    };
    RFQCreate: {
      title: string;
      notes?: string;
      lines?: components["schemas"]["RFQLineCreate"][];
    };
    RFQ: {
      id?: string;
      buyerId?: string;
      title?: string;
      notes?: string;
      /** @enum {string} */
      status?: "draft" | "issued" | "closed" | "awarded" | "cancelled";
      attachments?: components["schemas"]["Attachment"][];
      lines?: components["schemas"]["RFQLine"][];
    };
    RFQLineCreate: {
      productId?: string | null;
      description: string;
      /** Format: double */
      quantity: number;
      uom: string;
      /** Format: double */
      targetPrice?: number | null;
    };
    RFQLine: components["schemas"]["RFQLineCreate"] & {
      id?: string;
    };
    QuoteCreate: {
      vendorId: string;
      /** @default USD */
      currency: string;
      /** Format: date-time */
      validUntil?: string;
      notes?: string;
      lines: components["schemas"]["QuoteLineCreate"][];
    };
    Quote: {
      id?: string;
      rfqId?: string;
      vendorId?: string;
      currency?: string;
      /** Format: date-time */
      validUntil?: string;
      /** @enum {string} */
      status?: "draft" | "submitted" | "accepted" | "rejected" | "expired";
      /** Format: double */
      subtotal?: number;
      /** Format: double */
      taxTotal?: number;
      /** Format: double */
      grandTotal?: number;
      lines?: components["schemas"]["QuoteLine"][];
    };
    QuoteLineCreate: {
      rfqLineId: string;
      productId?: string | null;
      description: string;
      /** Format: double */
      quantity: number;
      uom: string;
      /** Format: double */
      unitPrice: number;
      /** Format: double */
      moq?: number | null;
      leadTimeDays?: number | null;
    };
    QuoteLine: components["schemas"]["QuoteLineCreate"] & {
      id?: string;
      /** Format: double */
      lineTotal?: number;
    };
    Order: {
      id?: string;
      buyerId?: string;
      quoteId?: string;
      /** @enum {string} */
      status?: "placed" | "confirmed" | "cancelled" | "fulfilled";
      currency?: string;
      /** Format: double */
      subtotal?: number;
      /** Format: double */
      taxTotal?: number;
      /** Format: double */
      grandTotal?: number;
    };
    Wallet: {
      id?: string;
      orgId?: string;
      currency?: string;
      /** Format: double */
      balance?: number;
    };
    WalletTransaction: {
      id?: string;
      walletId?: string;
      /** @enum {string} */
      type?: "topup" | "debit" | "refund";
      /** Format: double */
      amount?: number;
      reference?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    Payment: {
      id?: string;
      orderId?: string;
      /** @enum {string} */
      method?: "wallet" | "gateway1";
      /** @enum {string} */
      status?: "initiated" | "succeeded" | "failed";
      /** Format: double */
      amount?: number;
      currency?: string;
      idempotencyKey?: string;
    };
    Attachment: {
      key?: string;
      url?: string;
      filename?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
