/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */

export interface QuoteLineCreate {
  description: string;
  /** @nullable */
  leadTimeDays?: number | null;
  /** @nullable */
  moq?: number | null;
  /** @nullable */
  productId?: string | null;
  quantity: number;
  rfqLineId: string;
  unitPrice: number;
  uom: string;
}
