/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  buyer: 'buyer',
  vendor: 'vendor',
  ops: 'ops',
  admin: 'admin',
} as const;
