/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  RFQCreate,
  RFQLine,
  RFQLineCreate,
  Rfq
} from '.././orval-schemas'
import { orvalMutator } from '../../../orval-mutator';



/**
 * @summary Create RFQ (Buyer)
 */
export const postRfqs = (
    rFQCreate: RFQCreate,
 ) => {
      
      
      return orvalMutator<Rfq>(
      {url: `/rfqs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rFQCreate
    },
      );
    }
  


export const getPostRfqsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqs>>, TError,{data: RFQCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postRfqs>>, TError,{data: RFQCreate}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRfqs>>, {data: RFQCreate}> = (props) => {
          const {data} = props ?? {};

          return  postRfqs(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRfqsMutationResult = NonNullable<Awaited<ReturnType<typeof postRfqs>>>
    export type PostRfqsMutationBody = RFQCreate
    export type PostRfqsMutationError = unknown

    /**
 * @summary Create RFQ (Buyer)
 */
export const usePostRfqs = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqs>>, TError,{data: RFQCreate}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postRfqs>>,
        TError,
        {data: RFQCreate},
        TContext
      > => {

      const mutationOptions = getPostRfqsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get RFQ
 */
export const getRfqsRfqId = (
    rfqId: string,
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<Rfq>(
      {url: `/rfqs/${rfqId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetRfqsRfqIdQueryKey = (rfqId: string,) => {
    return [`/rfqs/${rfqId}`] as const;
    }

    
export const getGetRfqsRfqIdQueryOptions = <TData = Awaited<ReturnType<typeof getRfqsRfqId>>, TError = unknown>(rfqId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqId>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRfqsRfqIdQueryKey(rfqId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRfqsRfqId>>> = ({ signal }) => getRfqsRfqId(rfqId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(rfqId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRfqsRfqIdQueryResult = NonNullable<Awaited<ReturnType<typeof getRfqsRfqId>>>
export type GetRfqsRfqIdQueryError = unknown

/**
 * @summary Get RFQ
 */
export const useGetRfqsRfqId = <TData = Awaited<ReturnType<typeof getRfqsRfqId>>, TError = unknown>(
 rfqId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqId>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRfqsRfqIdQueryOptions(rfqId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Add RFQ line
 */
export const postRfqsRfqIdLines = (
    rfqId: string,
    rFQLineCreate: RFQLineCreate,
 ) => {
      
      
      return orvalMutator<RFQLine>(
      {url: `/rfqs/${rfqId}/lines`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rFQLineCreate
    },
      );
    }
  


export const getPostRfqsRfqIdLinesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdLines>>, TError,{rfqId: string;data: RFQLineCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdLines>>, TError,{rfqId: string;data: RFQLineCreate}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRfqsRfqIdLines>>, {rfqId: string;data: RFQLineCreate}> = (props) => {
          const {rfqId,data} = props ?? {};

          return  postRfqsRfqIdLines(rfqId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRfqsRfqIdLinesMutationResult = NonNullable<Awaited<ReturnType<typeof postRfqsRfqIdLines>>>
    export type PostRfqsRfqIdLinesMutationBody = RFQLineCreate
    export type PostRfqsRfqIdLinesMutationError = unknown

    /**
 * @summary Add RFQ line
 */
export const usePostRfqsRfqIdLines = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdLines>>, TError,{rfqId: string;data: RFQLineCreate}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postRfqsRfqIdLines>>,
        TError,
        {rfqId: string;data: RFQLineCreate},
        TContext
      > => {

      const mutationOptions = getPostRfqsRfqIdLinesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Issue RFQ (moves from draft→issued)
 */
export const postRfqsRfqIdIssue = (
    rfqId: string,
 ) => {
      
      
      return orvalMutator<void>(
      {url: `/rfqs/${rfqId}/issue`, method: 'POST'
    },
      );
    }
  


export const getPostRfqsRfqIdIssueMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdIssue>>, TError,{rfqId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdIssue>>, TError,{rfqId: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRfqsRfqIdIssue>>, {rfqId: string}> = (props) => {
          const {rfqId} = props ?? {};

          return  postRfqsRfqIdIssue(rfqId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRfqsRfqIdIssueMutationResult = NonNullable<Awaited<ReturnType<typeof postRfqsRfqIdIssue>>>
    
    export type PostRfqsRfqIdIssueMutationError = unknown

    /**
 * @summary Issue RFQ (moves from draft→issued)
 */
export const usePostRfqsRfqIdIssue = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdIssue>>, TError,{rfqId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postRfqsRfqIdIssue>>,
        TError,
        {rfqId: string},
        TContext
      > => {

      const mutationOptions = getPostRfqsRfqIdIssueMutationOptions(options);

      return useMutation(mutationOptions);
    }
    