/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  Quote,
  QuoteCreate
} from '.././orval-schemas'
import { orvalMutator } from '../../../orval-mutator';



/**
 * @summary List quotes for RFQ (Buyer view)
 */
export const getRfqsRfqIdQuotes = (
    rfqId: string,
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<Quote[]>(
      {url: `/rfqs/${rfqId}/quotes`, method: 'GET', signal
    },
      );
    }
  

export const getGetRfqsRfqIdQuotesQueryKey = (rfqId: string,) => {
    return [`/rfqs/${rfqId}/quotes`] as const;
    }

    
export const getGetRfqsRfqIdQuotesQueryOptions = <TData = Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>, TError = unknown>(rfqId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRfqsRfqIdQuotesQueryKey(rfqId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>> = ({ signal }) => getRfqsRfqIdQuotes(rfqId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(rfqId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRfqsRfqIdQuotesQueryResult = NonNullable<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>>
export type GetRfqsRfqIdQuotesQueryError = unknown

/**
 * @summary List quotes for RFQ (Buyer view)
 */
export const useGetRfqsRfqIdQuotes = <TData = Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>, TError = unknown>(
 rfqId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRfqsRfqIdQuotes>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRfqsRfqIdQuotesQueryOptions(rfqId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Submit quote (Vendor)
 */
export const postRfqsRfqIdQuotes = (
    rfqId: string,
    quoteCreate: QuoteCreate,
 ) => {
      
      
      return orvalMutator<Quote>(
      {url: `/rfqs/${rfqId}/quotes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: quoteCreate
    },
      );
    }
  


export const getPostRfqsRfqIdQuotesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>, TError,{rfqId: string;data: QuoteCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>, TError,{rfqId: string;data: QuoteCreate}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>, {rfqId: string;data: QuoteCreate}> = (props) => {
          const {rfqId,data} = props ?? {};

          return  postRfqsRfqIdQuotes(rfqId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRfqsRfqIdQuotesMutationResult = NonNullable<Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>>
    export type PostRfqsRfqIdQuotesMutationBody = QuoteCreate
    export type PostRfqsRfqIdQuotesMutationError = unknown

    /**
 * @summary Submit quote (Vendor)
 */
export const usePostRfqsRfqIdQuotes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>, TError,{rfqId: string;data: QuoteCreate}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postRfqsRfqIdQuotes>>,
        TError,
        {rfqId: string;data: QuoteCreate},
        TContext
      > => {

      const mutationOptions = getPostRfqsRfqIdQuotesMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Buyer accepts a quote (awards RFQ)
 */
export const postRfqsRfqIdQuotesQuoteIdAccept = (
    rfqId: string,
    quoteId: string,
 ) => {
      
      
      return orvalMutator<void>(
      {url: `/rfqs/${rfqId}/quotes/${quoteId}/accept`, method: 'POST'
    },
      );
    }
  


export const getPostRfqsRfqIdQuotesQuoteIdAcceptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>, TError,{rfqId: string;quoteId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>, TError,{rfqId: string;quoteId: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>, {rfqId: string;quoteId: string}> = (props) => {
          const {rfqId,quoteId} = props ?? {};

          return  postRfqsRfqIdQuotesQuoteIdAccept(rfqId,quoteId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRfqsRfqIdQuotesQuoteIdAcceptMutationResult = NonNullable<Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>>
    
    export type PostRfqsRfqIdQuotesQuoteIdAcceptMutationError = unknown

    /**
 * @summary Buyer accepts a quote (awards RFQ)
 */
export const usePostRfqsRfqIdQuotesQuoteIdAccept = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>, TError,{rfqId: string;quoteId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postRfqsRfqIdQuotesQuoteIdAccept>>,
        TError,
        {rfqId: string;quoteId: string},
        TContext
      > => {

      const mutationOptions = getPostRfqsRfqIdQuotesQuoteIdAcceptMutationOptions(options);

      return useMutation(mutationOptions);
    }
    