/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  Order,
  PostOrdersBody
} from '.././orval-schemas'
import { orvalMutator } from '../../../orval-mutator';



/**
 * @summary Create order from accepted quote
 */
export const postOrders = (
    postOrdersBody: PostOrdersBody,
 ) => {
      
      
      return orvalMutator<Order>(
      {url: `/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postOrdersBody
    },
      );
    }
  


export const getPostOrdersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrders>>, TError,{data: PostOrdersBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postOrders>>, TError,{data: PostOrdersBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrders>>, {data: PostOrdersBody}> = (props) => {
          const {data} = props ?? {};

          return  postOrders(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostOrdersMutationResult = NonNullable<Awaited<ReturnType<typeof postOrders>>>
    export type PostOrdersMutationBody = PostOrdersBody
    export type PostOrdersMutationError = unknown

    /**
 * @summary Create order from accepted quote
 */
export const usePostOrders = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrders>>, TError,{data: PostOrdersBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postOrders>>,
        TError,
        {data: PostOrdersBody},
        TContext
      > => {

      const mutationOptions = getPostOrdersMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get order
 */
export const getOrdersOrderId = (
    orderId: string,
 signal?: AbortSignal
) => {
      
      
      return orvalMutator<Order>(
      {url: `/orders/${orderId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetOrdersOrderIdQueryKey = (orderId: string,) => {
    return [`/orders/${orderId}`] as const;
    }

    
export const getGetOrdersOrderIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrdersOrderId>>, TError = unknown>(orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrdersOrderId>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersOrderIdQueryKey(orderId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrdersOrderId>>> = ({ signal }) => getOrdersOrderId(orderId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrdersOrderId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrdersOrderIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrdersOrderId>>>
export type GetOrdersOrderIdQueryError = unknown

/**
 * @summary Get order
 */
export const useGetOrdersOrderId = <TData = Awaited<ReturnType<typeof getOrdersOrderId>>, TError = unknown>(
 orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrdersOrderId>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOrdersOrderIdQueryOptions(orderId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



