spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/p4_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Use 'create-drop' for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Feature Flags for Dev Profile
feature:
  flags:
    catalog:
      publicBrowse: true
    search:
      enabled: true
    rfq:
      enabled: true
    quote:
      vendorConsole:
        enabled: true
    orders:
      checkout: true
    payments:
      gateway1: true
    wallet:
      basic: true
    invoice:
      vat: true
    loyalty:
      core: true
    credit:
      controls: true

# Database Seeding Configuration for Dev Profile
app:
  seed:
    enabled: true

# R2 Configuration for Dev Profile (mock values)
r2:
  access:
    key:
      id: ${R2_ACCESS_KEY_ID:dev-access-key}
  secret:
    access:
      key: ${R2_SECRET_ACCESS_KEY:dev-secret-key}
  bucket:
    name: ${R2_BUCKET:p4-dev-assets}
  endpoint:
    url: ${R2_ENDPOINT_URL:http://localhost:9000}