spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/p4_test}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recreate schema for tests
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Database Seeding Configuration for Tests
app:
  seed:
    enabled: true

# Backblaze B2 Configuration for Tests (mock values)
b2:
  account:
    id: ${B2_ACCOUNT_ID:test-account-id}
  application:
    key:
      id: ${B2_APPLICATION_KEY_ID:test-key-id}
  secret:
    access:
      key: ${B2_APPLICATION_KEY:test-secret-key}
  bucket:
    name: ${B2_BUCKET:p4-test-assets}
  endpoint:
    url: ${B2_ENDPOINT_URL:https://api.backblazeb2.com}