spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-damp-feather-adc322wz-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:***REMOVED***}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslmode: require
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Feature Flags for Neon Profile
feature:
  flags:
    catalog:
      publicBrowse: ${FEATURE_CATALOG_PUBLIC_BROWSE:true}
    search:
      enabled: ${FEATURE_SEARCH_ENABLED:true}

# Database Seeding Configuration for Neon Profile
app:
  seed:
    enabled: ${SEED_ENABLED:false}