spring:
  application:
    name: p4-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/p4_marketplace
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# R2 Configuration for Media Storage
r2:
  access:
    key: ${R2_ACCESS_KEY:your-r2-access-key}
  secret:
    key: ${R2_SECRET_KEY:your-r2-secret-key}
  bucket:
    name: ${R2_BUCKET_NAME:p4-prod-assets}
  endpoint: ${R2_ENDPOINT:https://your-account-id.r2.cloudflarestorage.com}

# Server Configuration
server:
  port: 8080

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Feature Flags Configuration
feature:
  flags:
    catalog:
      publicBrowse: ${FEATURE_CATALOG_PUBLIC_BROWSE:true}
    search:
      enabled: ${FEATURE_SEARCH_ENABLED:true}