spring:
  application:
    name: p4-backend
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Use 'create-drop' for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Backblaze B2 Configuration for Media Storage
b2:
  account:
    id: ${B2_ACCOUNT_ID:}
  application:
    key:
      id: ${B2_APPLICATION_KEY_ID:}
  secret:
    access:
      key: ${B2_APPLICATION_KEY:}
  bucket:
    name: ${B2_BUCKET:p4-prod-assets}
  endpoint:
    url: ${B2_ENDPOINT_URL:https://api.backblazeb2.com}

# Server Configuration
server:
  port: 8080

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true

# Feature Flags Configuration
feature:
  flags:
    catalog:
      publicBrowse: ${FEATURE_CATALOG_PUBLIC_BROWSE:false}
    search:
      enabled: ${FEATURE_SEARCH_ENABLED:false}
    rfq:
      enabled: ${FEATURE_RFQ_ENABLED:false}
    quote:
      vendorConsole:
        enabled: ${FEATURE_QUOTE_VENDOR_CONSOLE_ENABLED:false}
    orders:
      checkout: ${FEATURE_ORDERS_CHECKOUT:false}
    payments:
      gateway1: ${FEATURE_PAYMENTS_GATEWAY1:false}
    wallet:
      basic: ${FEATURE_WALLET_BASIC:false}
    invoice:
      vat: ${FEATURE_INVOICE_VAT:false}
    loyalty:
      core: ${FEATURE_LOYALTY_CORE:false}
    credit:
      controls: ${FEATURE_CREDIT_CONTROLS:false}

# Database Seeding Configuration
app:
  seed:
    enabled: ${SEED_ENABLED:false}

---
spring:
  config:
    activate:
      on-profile: prod

# Feature flags for production
feature:
  flags:
    catalog:
      publicBrowse: ${FEATURE_CATALOG_PUBLIC_BROWSE:false}
    search:
      enabled: ${FEATURE_SEARCH_ENABLED:false}
    rfq:
      enabled: ${FEATURE_RFQ_ENABLED:false}
    quote:
      vendorConsole:
        enabled: ${FEATURE_QUOTE_VENDOR_CONSOLE_ENABLED:false}
    orders:
      checkout: ${FEATURE_ORDERS_CHECKOUT:false}
    payments:
      gateway1: ${FEATURE_PAYMENTS_GATEWAY1:false}
    wallet:
      basic: ${FEATURE_WALLET_BASIC:false}
    invoice:
      vat: ${FEATURE_INVOICE_VAT:false}
    loyalty:
      core: ${FEATURE_LOYALTY_CORE:false}
    credit:
      controls: ${FEATURE_CREDIT_CONTROLS:false}

# R2 Configuration for production
r2:
  access:
    key:
      id: ${R2_ACCESS_KEY_ID}
  secret:
    access:
      key: ${R2_SECRET_ACCESS_KEY}
  bucket:
    name: ${R2_BUCKET}
  endpoint:
    url: ${R2_ENDPOINT_URL}