/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Mini-MVP API
 * Minimal endpoints for **Catalog → RFQ → Quote → Order → Wallet Pay**. Security is JWT bearer for authenticated flows. Public catalog endpoints are open but may be feature-flagged.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  Payment,
  PostOrdersOrderIdPayWalletBody
} from '.././orval-schemas'
import { orvalMutator } from '../../../orval-mutator';



/**
 * @summary Pay order using wallet
 */
export const postOrdersOrderIdPayWallet = (
    orderId: string,
    postOrdersOrderIdPayWalletBody: PostOrdersOrderIdPayWalletBody,
 ) => {
      
      
      return orvalMutator<Payment>(
      {url: `/orders/${orderId}/pay/wallet`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postOrdersOrderIdPayWalletBody
    },
      );
    }
  


export const getPostOrdersOrderIdPayWalletMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>, TError,{orderId: string;data: PostOrdersOrderIdPayWalletBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>, TError,{orderId: string;data: PostOrdersOrderIdPayWalletBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>, {orderId: string;data: PostOrdersOrderIdPayWalletBody}> = (props) => {
          const {orderId,data} = props ?? {};

          return  postOrdersOrderIdPayWallet(orderId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostOrdersOrderIdPayWalletMutationResult = NonNullable<Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>>
    export type PostOrdersOrderIdPayWalletMutationBody = PostOrdersOrderIdPayWalletBody
    export type PostOrdersOrderIdPayWalletMutationError = unknown

    /**
 * @summary Pay order using wallet
 */
export const usePostOrdersOrderIdPayWallet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>, TError,{orderId: string;data: PostOrdersOrderIdPayWalletBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postOrdersOrderIdPayWallet>>,
        TError,
        {orderId: string;data: PostOrdersOrderIdPayWalletBody},
        TContext
      > => {

      const mutationOptions = getPostOrdersOrderIdPayWalletMutationOptions(options);

      return useMutation(mutationOptions);
    }
    